### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 300
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 500
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "7193ddd5936648d2aa2abbe45756981d",
  "accountNumber": "1000000003",
  "amount": 50000
}

### query transaction
GET http://localhost:8080/transaction/8c8f0f4e2a1f4e8cb41408e8ca846f42